### ISSUE TITLE
about the feature extraction??

### ISSUE THREAD

**Issue by v3551G** [jeya-maria-jose/Cuff_less_BP_Prediction#3]
1.  I noticed a feature named 'alpha' in your file - feature_extraction_xx.m, does thie feature has any Physiological significance？ could you give any link about this feature definition?
2.  S=real(ifft(fft(ppg))), can you tell me the function of this code?
     thank you very much! Waiting your reply.

**Comment by jeya-maria-jose** [comment]
@v3551G 
1. Yes, it is called Womersley number. Please check this out : https://www.ncbi.nlm.nih.gov/pubmed/31051486
2. I think you left a couple of lines there. The exact code is as follows:
`Yy = fft(O1P);
Z=Yy(1);
Yy(1)=0;
S=real(ifft(Yy));`
So, here we convert the PPG signal to frequency domain and set the DC component to zero so that we only have the AC components of the signal. After that we convert it back to time domain and find the peaks of the signal ( in the later parts of the code as seen in feature_extraction_xx.m ) which helps us to find meu, which helps us find alpha.
