### ISSUE TITLE
The part of Deep Learning 

### ISSUE THREAD

**Issue by hldqiuye123** [jeya-maria-jose/Cuff_less_BP_Prediction#6]
Is that also extract the  fixed features point from ecg or ppg? or put the whole signal of these to network depend on the cycle or other factors？

**Comment by jeya-maria-jose** [comment]
For the deep learning part, we did not extract fixed features. We fed in the entire signal and got the feature output from the CNN and used it for regression.

**Comment by hldqiuye123** [comment]
> For the deep learning part, we did not extract fixed features. We fed in the entire signal and got the feature output from the CNN and used it for regression.

Thank your reply.
I noticed that the custom_data2.py have four labels including 'sbp','dbp','mbp','cla' .But the dataset only have one label called BP,How did the four labels compute ? And how many points of ppg or ecg match one group of label ?

**Comment by jeya-maria-jose** [comment]
So , from the BP signal, we find the average of all the local minima which is DBP and the average of all the local maxima is SBP. MAP can be thought of as an average of the two. Refer to the paper for the exact formulation. You can disregard the 'cla' column as that was just to classify the signals into separate classes depending on thresholds set on the MAP measurement.

We take the first 1000 samples of ppg, ecg and bp data so that the time frame is consistent between the signals and the ground truth (BP).

**Comment by hldqiuye123** [comment]
> So , from the BP signal, we find the average of all the local minima which is DBP and the average of all the local maxima is SBP. MAP can be thought of as an average of the two. Refer to the paper for the exact formulation. You can disregard the 'cla' column as that was just to classify the signals into separate classes depending on thresholds set on the MAP measurement.
> 
> We take the first 1000 samples of ppg, ecg and bp data so that the time frame is consistent between the signals and the ground truth (BP).

Ok, so the label is 'sbp','dbp','mbp' and the train dataset is two thousand points of ecg and ppg. Could you provide specific example of bp_train_new.csv 、bp_test_new.csv and checkN.csv?

**Comment by jeya-maria-jose** [comment]
https://drive.google.com/drive/folders/1n24ahZCxAAdkkmCfVrQeZXsSl4w0P6Jg?usp=sharing

Please look inside the GT folder.
